[ENV_setting]
# Specify the training GPU index
specify_gpu_index=0
# GPU number of model training
num_gpus=1
# Training model path in local
model_name_or_path=/app/gemma-3-12b-it
# Path of aiDAPTIVCache
nvme_path=/mnt/nvme0
# Password of root
pwd=phison

[Performance_test]
# Start batch size of performance test
start_bs=1
# End batch size of performance test
end_bs=100
# Sequence length while training LLM Model
seq_len=2048
# Expect training time in hour
training_hour=0.1
# Enable Triton
triton=True