name: container
services:
  phison-finetune:
    container_name: MW205_finetune
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              device_ids:
                - MIG-21a0bb79-3b1e-5c87-b27d-d5e07f6e635b
    image: aidaptiv:vNXUN_2_05_A1
    ipc: host
    networks:
      default: null
    privileged: true
    runtime: nvidia
    stdin_open: true
    tty: true
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - type: bind
        source: /usr/local/models
        target: /app
      - type: bind
        source: /mnt/nvme0
        target: /mnt/nvme0
      - type: bind
        source: /dev/mapper
        target: /dev/mapper
      - type: bind
        source: /var/lock
        target: /var/lock
      - type: bind
        source: /home/user
        target: /user
      - type: bind
        source: /workspace/vllm-observability-lab/finetune/configs
        target: /workspace/finetune/configs
        read_only: true
      - type: bind
        source: /workspace/vllm-observability-lab/finetune/datasets
        target: /workspace/finetune/datasets
        read_only: true
      - type: bind
        source: /workspace/vllm-observability-lab/finetune/toolkit
        target: /workspace/finetune/toolkit
        read_only: true
      - type: bind
        source: /workspace/vllm-observability-lab/finetune/runs
        target: /workspace/finetune/runs
networks:
  default:
    name: container_default
